name: Integration test
on:
  pull_request:
    branches:
      master

jobs:
  build:
    name: Run example
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and cache
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: gripmock:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Run Simple Example
      run: docker run --rm --entrypoint example/simple/entrypoint.sh gripmock:test
        
    - name: Run Advanced Example
      run: docker run --rm --entrypoint example/advanced/entrypoint.sh gripmock:test
        
    - name: Run Stream Example
      run: docker run --rm --entrypoint example/stream/entrypoint.sh gripmock:test
        
    - name: Run WKT Example
      run: docker run --rm --entrypoint example/well_known_types/entrypoint.sh gripmock:test
        
    - name: Run Multi Package Example
      run: docker run --rm --entrypoint example/multi-package/entrypoint.sh gripmock:test
        
    - name: Run Multi Files Example
      run: docker run --rm --entrypoint example/multi-files/entrypoint.sh gripmock:test
        
    - name: Run one-of Example
      run: docker run --rm --entrypoint example/one-of/entrypoint.sh gripmock:test
        
    - name: Run stub subfolders example
      run: docker run --rm --entrypoint example/stub-subfolders/entrypoint.sh gripmock:test
    - name: Run gzip example
      uses: ./
      with:
        entrypoint: example/simple-with-gzip/entrypoint.sh
